// AUTO-GENERATED by tools/convert.py from Losung_2026_XML.zip.
// Do not edit manually — re-run the converter instead.
import Toybox.Lang;
(:glance)
module LosungIndex {
    function jsonResForMonth(year as Number, month as Number) as Lang.ResourceId or Null {
        var key = year * 100 + month;
        switch (key) {
            case 202601: return Rez.JsonData.L_202601;
            case 202602: return Rez.JsonData.L_202602;
            case 202603: return Rez.JsonData.L_202603;
            case 202604: return Rez.JsonData.L_202604;
            case 202605: return Rez.JsonData.L_202605;
            case 202606: return Rez.JsonData.L_202606;
            case 202607: return Rez.JsonData.L_202607;
            case 202608: return Rez.JsonData.L_202608;
            case 202609: return Rez.JsonData.L_202609;
            case 202610: return Rez.JsonData.L_202610;
            case 202611: return Rez.JsonData.L_202611;
            case 202612: return Rez.JsonData.L_202612;
        }
        return null;
    }
}
