#!/usr/bin/env python3
"""Convert Losungen XML into per-day Connect IQ resources.

Glances on the FR955 only have 64 KB of memory; loading the full year as
JSON blows that budget. Instead we emit one tiny string resource per day
and a generated Monkey C lookup that maps month*100+day to the right
Rez.Strings symbol. The glance loads only today's string (~250 bytes).

Use --filter-past to drop entries whose date already lies before today
(Europe/Berlin). The committed resource file keeps the full year; the
filter is applied at build time so the .prg only carries the days that
the user can still see.
"""
import argparse
import datetime
import re
import sys
import xml.etree.ElementTree as ET
import zoneinfo
from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parent.parent
XML_DIR = ROOT / "xml_extracted"
DAYS_XML = ROOT / "garmin/resources/strings/days.xml"
INDEX_MC = ROOT / "garmin/source/LosungIndex.mc"

SEP = "|"  # verified absent from input
BERLIN = zoneinfo.ZoneInfo("Europe/Berlin")


def locate_xml() -> Path:
    matches = sorted(XML_DIR.glob("Losungen Free *.xml"))
    if not matches:
        sys.exit(f"No 'Losungen Free *.xml' in {XML_DIR}. Unzip the Losung_YYYY_XML.zip first.")
    if len(matches) > 1:
        sys.exit(f"Multiple Losungen XMLs found in {XML_DIR}: {[p.name for p in matches]}")
    return matches[0]


def parse(xml_path: Path) -> tuple[int, list[tuple[int, int, int, str, str, str, str]]]:
    tree = ET.parse(xml_path)
    out = []
    years: set[int] = set()
    for item in tree.getroot().findall("Losungen"):
        datum = item.findtext("Datum") or ""
        m = re.match(r"(\d{4})-(\d{2})-(\d{2})", datum)
        if not m:
            continue
        year = int(m.group(1))
        month = int(m.group(2))
        day = int(m.group(3))
        years.add(year)
        ot_ref = (item.findtext("Losungsvers") or "").strip()
        ot_text = (item.findtext("Losungstext") or "").strip()
        nt_ref = (item.findtext("Lehrtextvers") or "").strip()
        nt_text = (item.findtext("Lehrtext") or "").strip()
        for field in (ot_ref, ot_text, nt_ref, nt_text):
            assert SEP not in field, datum
        out.append((year, month, day, ot_ref, ot_text, nt_ref, nt_text))
    if not out:
        sys.exit(f"No <Losungen> entries parsed from {xml_path.name}")
    if len(years) != 1:
        sys.exit(f"Expected a single year in {xml_path.name}, found {sorted(years)}")
    return years.pop(), out


def filter_past(
    entries: list[tuple[int, int, int, str, str, str, str]],
) -> list[tuple[int, int, int, str, str, str, str]]:
    today = datetime.datetime.now(BERLIN).date()
    kept = [e for e in entries if datetime.date(e[0], e[1], e[2]) >= today]
    return kept


def generated_notice(source_name: str, filtered: bool) -> str:
    head = f"// AUTO-GENERATED by tools/convert.py from {source_name}."
    if filtered:
        today = datetime.datetime.now(BERLIN).date().isoformat()
        head += f"\n// Filtered to dates >= {today} (Europe/Berlin)."
    head += "\n// Do not edit manually — re-run the converter instead."
    return head + "\n"


def write_strings(
    entries: list[tuple[int, int, int, str, str, str, str]], notice: str
) -> None:
    DAYS_XML.parent.mkdir(parents=True, exist_ok=True)
    lines = ['<?xml version="1.0" encoding="UTF-8"?>', "<strings>"]
    lines.append(f"    <!-- {notice.strip().splitlines()[0][3:]} -->")
    for _y, month, day, ot_ref, ot_text, nt_ref, nt_text in entries:
        sid = f"D_{month:02d}{day:02d}"
        body = escape(SEP.join([ot_ref, ot_text, nt_ref, nt_text]))
        # scope="glance" links the symbol into the glance binary; without it,
        # any Rez.Strings.D_* reference from glance code silently produces a
        # blank glance render even with a tiny resource table.
        lines.append(f'    <string scope="glance" id="{sid}">{body}</string>')
    lines.append("</strings>")
    DAYS_XML.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_index(
    entries: list[tuple[int, int, int, str, str, str, str]], notice: str
) -> None:
    INDEX_MC.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        notice,
        "import Toybox.Lang;\n",
        "(:glance)\n",
        "module LosungIndex {\n",
    ]
    lines.append(
        "    function resForDay(month as Number, day as Number) as Lang.ResourceId or Null {\n"
    )
    lines.append("        var key = month * 100 + day;\n")
    lines.append("        switch (key) {\n")
    for _y, month, day, *_ in entries:
        key = month * 100 + day
        sid = f"D_{month:02d}{day:02d}"
        lines.append(f"            case {key}: return Rez.Strings.{sid};\n")
        # `return` makes implicit fallthrough impossible; no break needed.
    lines.append("        }\n        return null;\n    }\n}\n")
    INDEX_MC.write_text("".join(lines), encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument(
        "--filter-past",
        action="store_true",
        help="Drop entries with date < today (Europe/Berlin). Used at build time to shrink the .prg.",
    )
    args = ap.parse_args()

    xml_path = locate_xml()
    year, entries = parse(xml_path)
    source_name = f"Losung_{year}_XML.zip"

    if args.filter_past:
        before = len(entries)
        entries = filter_past(entries)
        print(f"Filtered past days: {before} -> {len(entries)} entries kept.")

    notice = generated_notice(source_name, filtered=args.filter_past)
    write_strings(entries, notice)
    write_index(entries, notice)
    print(
        f"Wrote {len(entries)} day strings -> {DAYS_XML.relative_to(ROOT)}\n"
        f"Wrote lookup -> {INDEX_MC.relative_to(ROOT)}"
    )


if __name__ == "__main__":
    main()
