#!/usr/bin/env python3
"""Convert Losungen XML into per-day Connect IQ resources.

Glances on the FR955 only have 64 KB of memory; loading the full year as
JSON blows that budget. Instead we emit one tiny string resource per day
and a generated Monkey C lookup that maps month*100+day to the right
Rez.Strings symbol. The glance loads only today's string (~250 bytes).
"""
import xml.etree.ElementTree as ET
import re
from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parent.parent
XML_PATH = ROOT / "xml_extracted" / "Losungen Free 2026.xml"
DAYS_XML = ROOT / "garmin/resources/strings/days.xml"
INDEX_MC = ROOT / "garmin/source/LosungIndex.mc"

SEP = "|"  # verified absent from input

GENERATED_NOTICE = (
    "// AUTO-GENERATED by tools/convert.py from Losung_2026_XML.zip.\n"
    "// Do not edit manually — re-run the converter instead.\n"
)


def parse() -> list[tuple[int, int, str, str]]:
    tree = ET.parse(XML_PATH)
    out = []
    for item in tree.getroot().findall("Losungen"):
        datum = item.findtext("Datum") or ""
        m = re.match(r"\d{4}-(\d{2})-(\d{2})", datum)
        if not m:
            continue
        month = int(m.group(1))
        day = int(m.group(2))
        ref = (item.findtext("Lehrtextvers") or "").strip()
        text = (item.findtext("Lehrtext") or "").strip()
        assert SEP not in ref and SEP not in text, datum
        out.append((month, day, ref, text))
    return out


def write_strings(entries: list[tuple[int, int, str, str]]) -> None:
    DAYS_XML.parent.mkdir(parents=True, exist_ok=True)
    lines = ['<?xml version="1.0" encoding="UTF-8"?>', "<strings>"]
    lines.append(f"    <!-- {GENERATED_NOTICE.strip().splitlines()[0][3:]} -->")
    for month, day, ref, text in entries:
        sid = f"D_{month:02d}{day:02d}"
        body = escape(f"{ref}{SEP}{text}")
        lines.append(f'    <string id="{sid}">{body}</string>')
    lines.append("</strings>")
    DAYS_XML.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_index(entries: list[tuple[int, int, str, str]]) -> None:
    INDEX_MC.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        GENERATED_NOTICE,
        "import Toybox.Lang;\n",
        "(:glance)\n",
        "module LosungIndex {\n",
    ]
    lines.append(
        "    function resForDay(month as Number, day as Number) as Lang.ResourceId or Null {\n"
    )
    lines.append("        var key = month * 100 + day;\n")
    lines.append("        switch (key) {\n")
    for month, day, _ref, _text in entries:
        key = month * 100 + day
        sid = f"D_{month:02d}{day:02d}"
        lines.append(f"            case {key}: return Rez.Strings.{sid};\n")
        # `return` makes implicit fallthrough impossible; no break needed.
    lines.append("        }\n        return null;\n    }\n}\n")
    INDEX_MC.write_text("".join(lines), encoding="utf-8")


def main() -> None:
    entries = parse()
    write_strings(entries)
    write_index(entries)
    print(
        f"Wrote {len(entries)} day strings -> {DAYS_XML.relative_to(ROOT)}\n"
        f"Wrote lookup -> {INDEX_MC.relative_to(ROOT)}"
    )


if __name__ == "__main__":
    main()
