#!/usr/bin/env python3
"""Convert Losungen XML into per-month Connect IQ JSON resources.

Older Connect IQ devices (CIQ 3.x) cap each module at 254 members. With one
string resource per day we hit ~370 members in Rez.Strings and the build
fails for those devices. Per-month JSON resources put 12 entries into
Rez.JsonData instead — well within the limit — and we still load only one
month (~7 KB) at a time, so the glance memory budget on the FR955 stays
intact.

Each month becomes one JSON file (`losungen_YYYY_MM.json`) shaped as
`{"<day>": [losungvers, losungtext, lehrtextvers, lehrtext], ...}`. The
generated `LosungIndex.mc` maps year*100+month to the matching
`Rez.JsonData.L_YYYYMM` symbol.

Use --filter-past to drop entries whose date already lies before today
(Europe/Berlin). The committed resource file keeps the full year; the
filter is applied at build time so the .prg only carries the days that
the user can still see.
"""
import argparse
import datetime
import json
import re
import sys
import xml.etree.ElementTree as ET
import zoneinfo
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
XML_DIR = ROOT / "xml_extracted"
JSON_DIR = ROOT / "garmin/resources/jsondata"
JSONDATA_XML = JSON_DIR / "jsondata.xml"
INDEX_MC = ROOT / "garmin/source/LosungIndex.mc"
LEGACY_DAYS_XML = ROOT / "garmin/resources/strings/days.xml"

BERLIN = zoneinfo.ZoneInfo("Europe/Berlin")


def locate_xml() -> Path:
    matches = sorted(XML_DIR.glob("Losungen Free *.xml"))
    if not matches:
        sys.exit(f"No 'Losungen Free *.xml' in {XML_DIR}. Unzip the Losung_YYYY_XML.zip first.")
    if len(matches) > 1:
        sys.exit(f"Multiple Losungen XMLs found in {XML_DIR}: {[p.name for p in matches]}")
    return matches[0]


def parse(xml_path: Path) -> tuple[int, list[tuple[int, int, int, str, str, str, str]]]:
    tree = ET.parse(xml_path)
    out = []
    years: set[int] = set()
    for item in tree.getroot().findall("Losungen"):
        datum = item.findtext("Datum") or ""
        m = re.match(r"(\d{4})-(\d{2})-(\d{2})", datum)
        if not m:
            continue
        year = int(m.group(1))
        month = int(m.group(2))
        day = int(m.group(3))
        years.add(year)
        ot_ref = (item.findtext("Losungsvers") or "").strip()
        ot_text = (item.findtext("Losungstext") or "").strip()
        nt_ref = (item.findtext("Lehrtextvers") or "").strip()
        nt_text = (item.findtext("Lehrtext") or "").strip()
        out.append((year, month, day, ot_ref, ot_text, nt_ref, nt_text))
    if not out:
        sys.exit(f"No <Losungen> entries parsed from {xml_path.name}")
    if len(years) != 1:
        sys.exit(f"Expected a single year in {xml_path.name}, found {sorted(years)}")
    return years.pop(), out


def filter_past(
    entries: list[tuple[int, int, int, str, str, str, str]],
) -> list[tuple[int, int, int, str, str, str, str]]:
    today = datetime.datetime.now(BERLIN).date()
    return [e for e in entries if datetime.date(e[0], e[1], e[2]) >= today]


def generated_notice(source_name: str, filtered: bool) -> str:
    head = f"// AUTO-GENERATED by tools/convert.py from {source_name}."
    if filtered:
        today = datetime.datetime.now(BERLIN).date().isoformat()
        head += f"\n// Filtered to dates >= {today} (Europe/Berlin)."
    head += "\n// Do not edit manually — re-run the converter instead."
    return head + "\n"


def write_jsondata(
    entries: list[tuple[int, int, int, str, str, str, str]], notice: str
) -> list[tuple[int, int]]:
    """Write one JSON file per (year, month). Returns sorted list of (year, month)."""
    JSON_DIR.mkdir(parents=True, exist_ok=True)
    # Wipe previously generated files so removed months don't linger.
    for old in JSON_DIR.glob("losungen_*.json"):
        old.unlink()

    by_month: dict[tuple[int, int], dict[str, list[str]]] = {}
    for year, month, day, ot_ref, ot_text, nt_ref, nt_text in entries:
        by_month.setdefault((year, month), {})[str(day)] = [ot_ref, ot_text, nt_ref, nt_text]

    months = sorted(by_month.keys())
    for (year, month), days_map in by_month.items():
        path = JSON_DIR / f"losungen_{year:04d}_{month:02d}.json"
        # Sort days numerically within each chunk so re-runs produce stable output.
        ordered = {k: days_map[k] for k in sorted(days_map.keys(), key=int)}
        path.write_text(
            json.dumps(ordered, ensure_ascii=False, separators=(",", ":")) + "\n",
            encoding="utf-8",
        )

    # Resource manifest. scope="glance" links these into the glance binary;
    # without it, glance code referencing Rez.JsonData.* compiles but loads nothing.
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        f"<!-- {notice.strip().splitlines()[0][3:]} -->",
        "<resources>",
    ]
    for year, month in months:
        sid = f"L_{year:04d}{month:02d}"
        fname = f"losungen_{year:04d}_{month:02d}.json"
        lines.append(f'    <jsonData scope="glance" id="{sid}" filename="{fname}"/>')
    lines.append("</resources>")
    JSONDATA_XML.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return months


def write_index(months: list[tuple[int, int]], notice: str) -> None:
    INDEX_MC.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        notice,
        "import Toybox.Lang;\n",
        "(:glance)\n",
        "module LosungIndex {\n",
        "    function jsonResForMonth(year as Number, month as Number) as Lang.ResourceId or Null {\n",
        "        var key = year * 100 + month;\n",
        "        switch (key) {\n",
    ]
    for year, month in months:
        key = year * 100 + month
        sid = f"L_{year:04d}{month:02d}"
        lines.append(f"            case {key}: return Rez.JsonData.{sid};\n")
    lines.append("        }\n        return null;\n    }\n}\n")
    INDEX_MC.write_text("".join(lines), encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument(
        "--filter-past",
        action="store_true",
        help="Drop entries with date < today (Europe/Berlin). Used at build time to shrink the .prg.",
    )
    args = ap.parse_args()

    xml_path = locate_xml()
    year, entries = parse(xml_path)
    source_name = f"Losung_{year}_XML.zip"

    if args.filter_past:
        before = len(entries)
        entries = filter_past(entries)
        print(f"Filtered past days: {before} -> {len(entries)} entries kept.")

    # Drop the legacy per-day strings file if it lingers from an older converter
    # version. The new build uses jsondata only.
    if LEGACY_DAYS_XML.exists():
        LEGACY_DAYS_XML.unlink()

    notice = generated_notice(source_name, filtered=args.filter_past)
    months = write_jsondata(entries, notice)
    write_index(months, notice)
    print(
        f"Wrote {len(entries)} entries across {len(months)} month(s) -> {JSON_DIR.relative_to(ROOT)}\n"
        f"Wrote lookup -> {INDEX_MC.relative_to(ROOT)}"
    )


if __name__ == "__main__":
    main()
